# Generated by Django 5.0.2 on 2024-03-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='criteria',
            table='Criteria',
        ),
    ]
