# Generated by Django 5.0.2 on 2024-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criteria', '0002_alter_criteria_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria_a',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='criteria_b',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='criteria_c',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='criteria_d',
            field=models.CharField(max_length=250),
        ),
    ]
