# Generated by Django 5.0.2 on 2024-03-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criteria', '0003_alter_criteria_criteria_a_alter_criteria_criteria_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=15)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
            ],
            options={
                'db_table': 'EvaluationDate',
            },
        ),
    ]
