# Generated by Django 5.0.1 on 2024-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_faculty',
            name='studentID',
            field=models.IntegerField(default=0),
        ),
    ]
