# Generated by Django 5.0.1 on 2024-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0003_faculty_subject_delete_add_faculty_faculty_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(default='1111', max_length=128),
        ),
    ]
