# Generated by Django 5.0.1 on 2024-02-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0004_faculty_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='first_name',
        ),
    ]
