# Generated by Django 5.0.1 on 2024-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0007_faculty_first_name_faculty_last_name'),
        ('Departments', '0002_alter_subject_subdescriptions_alter_subject_subname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='faculties', to='Departments.subject'),
        ),
    ]
