# Generated by Django 5.0.1 on 2024-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0009_remove_faculty_subjects'),
        ('Departments', '0002_alter_subject_subdescriptions_alter_subject_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='faculties', to='Departments.subject'),
        ),
    ]
