# Generated by Django 5.0.1 on 2024-02-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0010_faculty_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
    ]
