# Generated by Django 5.0.1 on 2024-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0012_faculty_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='selected_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/'),
        ),
    ]
