# Generated by Django 5.0.2 on 2024-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0017_facultysubject'),
        ('Departments', '0004_remove_semester_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultysubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facultysubject',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facultysubject',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='facultysubject',
            unique_together={('faculty', 'subject', 'semester', 'year')},
        ),
    ]
