# Generated by Django 5.0.2 on 2024-05-12 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0018_alter_facultysubject_unique_together_and_more'),
        ('Departments', '0004_remove_semester_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='newEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('criteria_A', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_B', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_C', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_D', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.subject')),
            ],
            options={
                'db_table': 'Subjects_Evaluation',
                'unique_together': {('faculty', 'subject', 'semester', 'year')},
            },
        ),
    ]
