# Generated by Django 5.0.2 on 2024-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0019_newevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevaluation',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=1),
        ),
    ]
