# Generated by Django 5.0.2 on 2024-05-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0020_alter_newevaluation_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newevaluation',
            unique_together=set(),
        ),
    ]
