# Generated by Django 5.0.2 on 2024-05-12 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0021_alter_newevaluation_unique_together'),
        ('Course_and_Students', '0005_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevaluation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_and_Students.student'),
        ),
    ]
