# Generated by Django 5.0.2 on 2024-05-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0025_alter_facultysubject_year'),
        ('Course_and_Students', '0007_alter_student_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevaluation',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_and_Students.admin'),
        ),
        migrations.AddField(
            model_name='newevaluation',
            name='year_level',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
