# Generated by Django 5.0.2 on 2024-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0026_newevaluation_admin_newevaluation_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevaluation',
            name='admin_id_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='newevaluation',
            name='student_id_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
