# Generated by Django 5.0.2 on 2024-05-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_faculty', '0028_newevaluation_course'),
        ('Course_and_Students', '0007_alter_student_year_level'),
        ('Departments', '0004_remove_semester_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newevaluation',
            unique_together={('student', 'admin', 'subject', 'semester', 'year')},
        ),
    ]
