# Generated by Django 5.0.2 on 2024-05-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0002_alter_subject_subdescriptions_alter_subject_subname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=1)),
            ],
        ),
    ]
