# Generated by Django 5.0.2 on 2024-05-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0003_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
    ]
