# Generated by Django 5.0.2 on 2024-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_and_Students', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
