# Generated by Django 5.0.2 on 2024-04-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_and_Students', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
