# Generated by Django 5.0.2 on 2024-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_and_Students', '0005_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
