# Generated by Django 5.0.2 on 2024-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_and_Students', '0006_student_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
